[project]
name = "edu-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.118.3",
    "gunicorn>=23.0.0",
    "orjson>=3.11.3",
    "uvicorn-worker>=0.4.0",
]
